"""add prompt_version and error_message to analyses

Revision ID: 34cdc35f039f
Revises: e7757e3d3794
Create Date: 2026-08-31 16:04:19.581447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cdc35f039f'
down_revision: Union[str, Sequence[str], None] = 'e7757e3d3794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('prompt_version', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'error_message')
    op.drop_column('analyses', 'prompt_version')
    # ### end Alembic commands ###
